# Generated by Django 4.1 on 2022-08-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subject1', models.CharField(blank=True, max_length=100, null=True)),
                ('subject2', models.CharField(blank=True, max_length=100, null=True)),
                ('subject3', models.CharField(blank=True, max_length=100, null=True)),
                ('author1', models.CharField(max_length=255)),
                ('author2', models.CharField(blank=True, max_length=255, null=True)),
                ('author3', models.CharField(blank=True, max_length=255, null=True)),
                ('is_translated', models.BooleanField()),
                ('translator1', models.CharField(blank=True, max_length=255, null=True)),
                ('translator2', models.CharField(blank=True, max_length=255, null=True)),
                ('translator3', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(max_length=255)),
                ('publish_year', models.CharField(max_length=4)),
                ('total_quantity', models.SmallIntegerField()),
                ('available_quantity', models.SmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(default='default_book.png', upload_to='books_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_date', models.DateField(auto_now_add=True)),
                ('return_due_date', models.DateField()),
                ('actual_return_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book_app.book')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_app.memberprofile')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='book_app.category'),
        ),
    ]
