# Generated by Django 4.1 on 2022-08-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbook',
            name='return_due_date',
            field=models.DateField(blank=True),
        ),
    ]
